String HTML() {
String html = "<!DOCTYPE html> <html>\n"
  "<head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\n"
  "<title>ESP32 Hello World</title>\n"
  "<style>html { font-family: Helvetica; display: inline-block; margin: 0px auto; text-align: center;}\n"
  "body{margin-top: 50px;} h1 {color: #444444;margin: 50px auto 30px;}\n"
  "p {font-size: 24px;color: #444444;margin-bottom: 10px;}\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div id=\"webpage\">\n"
  "<span style=\"color: red; font-size: 32px\">Merry </span><span style=\"color: green; font-size: 32px\">Christmas</span>\n"
  "</br>"
  "<label for=\"primary\">Single Color: </label>"
  "<input type=\"color\" value=\"#e66465\" name=\"primary\" id=\"primary\">"
  "</div>\n"
  "<div>\n"
  "<label for=\"random\">Random Colors: </label>"
  "<input type=\"radio\" name=\"random\" id=\"random\"/>"
  "</br>"
  "<label for=\"random\">Spiral: </label>"
  "<input type=\"radio\" name=\"spiral\" id=\"spiral\"/>"
  "</br>"
  "<label for=\"Xmas\">Christmas Colors: </label>"
  "<input type=\"radio\" name=\"Xmas\" id=\"Xmas\"/>"
  "</div>"
  "<button id=\"clear\">Clear Current Action</button>"
  "</body>\n"
  "</html>\n"
  ;
  return html;
}
