String MainJS() {
    String script = "<script>"
    "let primaryColor;"
    "let random;"
    "let spiral;"
    "let spiralRandom;"
    "let Xmas;"
    "let clear;"
    "let number;"
    "let currentBrightness;"
    "let dot;"
    "const defaultColor = \"#0000ff\";"
    "var color;"
    "window.addEventListener(\"load\", startup, false);"
    "function startup() {"
        "primaryColor = document.querySelector(\"#primary\");"
        "primaryColor.value = defaultColor;"
        "primaryColor.addEventListener(\"change\", updatePrimary, false);"
        "random = document.querySelector(\"#random\");"
        "random.addEventListener(\"change\", setRandom, false);"
        "spiral = document.querySelector(\"#spiral\");"
        "spiral.addEventListener(\"change\", setSpiral, false);"
        "spiralRandom = document.querySelector(\"#spiralRandom\");"
        "spiralRandom.addEventListener(\"change\", setRandomSpiral, false);"
        "Xmas = document.querySelector(\"#Xmas\");"
        "Xmas.addEventListener(\"change\", setXmas, false);"
        "clear = document.querySelector(\"#clear\");"
        "clear.addEventListener(\"click\", clearLED, false);"
        "number = document.querySelector(\"#number\");"
        "number.addEventListener(\"change\", setBrightness, false);"
        "currentBrightness = document.querySelector(\"#currentBrightness\");"
        "dot = document.querySelector(\"#dot\");"
        "dot.addEventListener(\"change\", setDot, false);"
    "}"
    "function convert(hex){"
        "const r = parseInt(hex.substr(1, 2), 16);"
        "const g = parseInt(hex.substr(3, 2), 16);"
        "const b = parseInt(hex.substr(5, 2), 16);"
        "return [r,g,b]"
    "}"
    "function updatePrimary(event){"
        "dot.checked = false;"
        "Xmas.checked = false;"
        "random.checked = false;"
        "spiral.checked = false;"
        "spiralRandom.checked = false;"
        "let rgb = convert(event.target.value);"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.4.1/primary?r=\" + rgb[0] + \"&g=\" + rgb[1] + \"&b=\" + rgb[2] , false);"
        "req.send(null);"
    "}"
    "function setRandom(){"
        "dot.checked = false;"
        "Xmas.checked = false;"
        "spiral.checked = false;"
        "spiralRandom.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.4.1/random\" , false);"
        "req.send(null);"
    "}"
    "function setSpiral(){"
        "dot.checked = false;"
        "random.checked = false;"
        "Xmas.checked = false;"
        "spiralRandom.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.4.1/spiral\" , false);"
        "req.send(null);"
    "}"
    "function setXmas(){"
        "dot.checked = false;"
        "spiral.checked = false;"
        "random.checked = false;"
        "spiralRandom.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.4.1/xmas\" , false);"
        "req.send(null);"
    "}"
    "function clearLED(){"
        "dot.checked = false;"
        "Xmas.checked = false;"
        "random.checked = false;"
        "spiral.checked = false;"
        "spiralRandom.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.4.1/clear\" , false);"
        "req.send(null);"
    "}"
    "function setRandomSpiral(){"
        "dot.checked = false;"
        "Xmas.checked = false;"
        "random.checked = false;"
        "spiral.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.4.1/random_spiral\" , false);"
        "req.send(null);"
    "}"
    "function setDot(){"
        "Xmas.checked = false;"
        "random.checked = false;"
        "spiral.checked = false;"
        "spiralRandom.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.4.1/dot\" , false);"
        "req.send(null);"
    "}"
    "function setBrightness(event){"
        "let req = new XMLHttpRequest();"
        "req.onreadystatechange = function() {"
            "currentBrightness.innerHTML = this.responseText;"
        "};"
        "req.open(\"GET\", \"http://192.168.4.1/brightness?b=\" + event.target.value , false);"
        "req.send(null);"
    "}"
    "</script>"    
    ;
    return script;
}


String SetDateJS() {
    String JS = 
    "<script>"
    "window.addEventListener(\"load\", startup, false);"
    "function startup() {"
        "dateInput = document.querySelector(\"#dateInput\");"
        "dateInput.addEventListener(\"change\", setDate, false);"
    "}"
    "function setDate(event) {"
        "let req = new XMLHttpRequest();"
        "let date = event.target.value;"
        "req.onreadystatechange = function() {"
            "if (req.readyState == XMLHttpRequest.DONE) {"
                "window.location.href = \"http://192.168.4.1/\";"
            "}"
        "};"
        "req.open(\"GET\", \"http://192.168.4.1/setDate?date=\" + date , false);"
        "req.send(null);"
    "}"
    "</script>"
    ;
    return JS;
}

String bDayJS() {
    String JS = 
    "<script>"
    "window.addEventListener(\"load\", startup, false);"
    "function startup() {"
        "button = document.querySelector(\"#mainPage\");"
        "button.addEventListener(\"click\", resetPage, false);"
    "}"
    "function resetPage() {"
        "let req = new XMLHttpRequest();"
         "req.onreadystatechange = function() {"
            "if (req.readyState == XMLHttpRequest.DONE) {"
                "window.location.href = \"http://192.168.4.1/\";"
            "}"
        "};"
        "req.open(\"GET\", \"http://192.168.4.1/resetPage\" , false);"
        "req.send(null);"
    "}"
    "</script>"
    ;
    return JS;
}