String JS() {
    String script = "<script>"
    "let primaryColor;"
    "let random;"
    "let spiral;"
    "let Xmas;"
    "let clear;"
    "const defaultColor = \"#0000ff\";"
    "var color;"
    "window.addEventListener(\"load\", startup, false);"
    "function startup() {"
        "primaryColor = document.querySelector(\"#primary\");"
        "primaryColor.value = defaultColor;"
        "primaryColor.addEventListener(\"change\", updatePrimary, false);"
        "random = document.querySelector(\"#random\");"
        "random.addEventListener(\"change\", setRandom, false);"
        "spiral = document.querySelector(\"#spiral\");"
        "spiral.addEventListener(\"change\", setSpiral, false);"
        "Xmas = document.querySelector(\"#Xmas\");"
        "Xmas.addEventListener(\"change\", setXmas, false);"
        "clear = document.querySelector(\"#clear\");"
        "clear.addEventListener(\"click\", clearLED, false);"
    "}"
    "function convert(hex){"
        "const r = parseInt(hex.substr(1, 2), 16);"
        "const g = parseInt(hex.substr(3, 2), 16);"
        "const b = parseInt(hex.substr(5, 2), 16);"
        "return [r,g,b]"
    "}"
    "function updatePrimary(event){"
        "Xmas.checked = false;"
        "random.checked = false;"
        "spiral.checked = false;"
        "let rgb = convert(event.target.value);"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.50.14/primary?r=\" + rgb[0] + \"&g=\" + rgb[1] + \"&b=\" + rgb[2] , false);"
        "req.send(null);"
    "}"
    "function setRandom(){"
        "Xmas.checked = false;"
        "spiral.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.50.14/random\" , false);"
        "req.send(null);"
    "}"
    "function setSpiral(){"
        "random.checked = false;"
        "Xmas.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.50.14/spiral\" , false);"
        "req.send(null);"
    "}"
    "function setXmas(){"
        "spiral.checked = false;"
        "random.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.50.14/xmas\" , false);"
        "req.send(null);"
    "}"
    "function clearLED(){"
        "Xmas.checked = false;"
        "random.checked = false;"
        "spiral.checked = false;"
        "let req = new XMLHttpRequest();"
        "req.open(\"GET\", \"http://192.168.50.14/clear\" , false);"
        "req.send(null);"
    "}"
    "</script>"    
    ;
    return script;
}